- name: Install Nginx
  yum: name=nginx state=present


- name: Start phpfpm
  service: name=php-fpm state=started

- name: Create directory for virtualhost
  file: dest=/srv/html state=directory

- name: Copy nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy index.php
  template: src=index.php dest=/srv/html/index.php

- name: Restart nginx
  service: name=nginx state=restarted
  
