- name: Install Nginx 
  apt: name=nginx state=present

- name: Create directory for virtualhost
  file: dest=/srv/{{ server_name }} state=directory

- name: Copy virtualhost config
  template: src=default.conf dest=/etc/nginx/conf.d/{{ server_name }}.conf

- name: Copy index.html
  template: src=index.html dest=/srv/{{ server_name}}/index.html
  notify: restart nginx
